bboard/urls.py
from django.urls import path, re_path

from bboard.models import Bb
from bboard.views import (index, BbCreateView,
                          BbByRubricView, BbDetailView,
                          BbDeleteView, BbRedirectView, edit, RubCreateView, rubrics, about,
                          edit_rubric, RubricDeleteView, Search, api_rubrics, api_rubric_detail, UserCreateView, )

app_name = 'bboard'

urlpatterns = [
    path('api/rubrics/<int:pk>/', api_rubric_detail),
    path('api/rubrics/', api_rubrics),
    path('add/', BbCreateView.as_view(), name='add'),
    path('update/<int:pk>/', edit, name='update'),
    path('rubrics/<int:pk>/edit/', edit_rubric, name='edit_rubric'),
    path('rubrics/<int:pk>/delete/', RubricDeleteView.as_view(), name='delete_rubric'),
    path('addrub/', RubCreateView.as_view(), name='addrub'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),
    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),
    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('detail/<int:year>/<int:month>/<int:day>/<int:pk>/',
         BbRedirectView.as_view(), name='old_detail'),
    path('rubrics/', rubrics, name='rubrics'),
    path('', index, name='index'),
    path('search/', Search.as_view(), name='search'),
    path('about/', about, name='about'),
    path('register/', UserCreateView.as_view(), name='user-register'),
]

drfsite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from women.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('api/v1/women/', WomenAPIList.as_view()),
    path('api/v1/women/<int:pk>/', WomenAPIUpdate.as_view()),
    path('api/v1/womendelete/<int:pk>/', WomenAPIDestroy.as_view()),
    path('api/v1/auth/', include('djoser.urls')),  # new
    re_path(r'^auth/', include('djoser.urls.authtoken')),  # new
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

samplesite/urls.py
from tempfile import template

from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include, reverse_lazy

from bboard.views import LoginUser, RegisterUser, ProfileUser, UserForgotPasswordView, UserPasswordResetConfirmView, \
    UserPasswordChangeView
from samplesite import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/login/', LoginUser.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/register/', RegisterUser.as_view(), name='register'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('', include('bboard.urls', namespace='bboard')),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
]
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bboard/models.py
from django.core import validators
from django.core.exceptions import ValidationError
from django.db import models



def is_active_default():
    return True


class MinMaxValueValidator:
    def __init__(self, min_value, max_value):
        self.min_value = min_value
        self.max_value = max_value

    def __call__(self, val):
        if val < self.min_value or val > self.max_value:
            raise ValidationError('Введённое число должно находиться в диапазоне от '
                                  '%(min)s до %(max)s',
                                  code='out_of_range',
                                  params={'min': self.min_value, 'max': self.max_value})


class RubricQuerySet(models.QuerySet):
    def order_by_bb_count(self):
        return super().annotate(
            cnt=models.Count('bb')
        ).order_by('-cnt')


class RubricManager(models.Manager):

    def get_queryset(self):
        return RubricQuerySet(self.model, using=self._db)

    def order_by_bb_count(self):
        return self.get_queryset().order_by_bb_count()


class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, unique=True,
                            verbose_name='Название')
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", null=True, default=None,
                              blank=True, verbose_name="Фото")
    objects = models.Manager.from_queryset(RubricQuerySet)()
    bbs = RubricManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/{self.pk}/"

    class Meta:
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'
        ordering = ['name', '-photo']


class BbManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('price')


class Bb(models.Model):
    KINDS = (
        (None, 'Выберите тип публикуемого объявления'),
        ('b', 'Куплю'),
        ('s', 'Продам'),
        ('c', 'Обменяю'),
    )

    kind = models.CharField(max_length=1, choices=KINDS, default='s')

    rubric = models.ForeignKey('Rubric', null=True, on_delete=models.CASCADE ,
                               verbose_name='Рубрика')
    title = models.CharField(max_length=50, verbose_name='Товар',
                             validators=[
                                 validators.RegexValidator(
                                     regex='^.{4,}$',
                                     message='Слишком мало букавак!',
                                     code='invalid',
                                 )
                             ],
                             error_messages={'invalid': 'Неправильное название товара!'}
                             )
    content = models.CharField(max_length=1000, null=True, blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=15, decimal_places=2,
                                null=True, blank=True, verbose_name='Цена', )
    published = models.DateTimeField(auto_now_add=True, db_index=True,
                                     verbose_name='Опубликовано')
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", default=None,
                              blank=True, verbose_name="Фото")

    objects = models.Manager()
    by_price = BbManager()

    def title_and_price(self):
        if self.price:
            return f'{self.title} ({self.price:.2f})'
        else:
            return self.title

    title_and_price.short_description = 'Название и цена'

    def __str__(self):
        return f'{self.title} ({self.price} тг.)'

    def clean(self):
        errors = {}
        if not self.content:
            errors['content'] = ValidationError('Укажите описание продаваемого товара')

        if self.price and self.price < 0:
            errors['price'] = ValidationError('Укажите неотрицательное значение цены')

        if errors:
            raise ValidationError(errors)

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['-published', 'title']
        get_latest_by = 'published'
        permissions = (("can_create", "Can create anything"),)


class UploadFiles(models.Model):
    file = models.FileField(upload_to='uploads_model')

bboard/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetConfirmView, PasswordResetView
from django.core.paginator import Paginator
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Count
from django.forms.formsets import ORDERING_FIELD_NAME
from django.http import HttpResponse, HttpResponseRedirect, HttpResponsePermanentRedirect, HttpResponseNotFound, \
    Http404, StreamingHttpResponse, FileResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.template import loader
from django.template.loader import get_template, render_to_string
from django.urls import reverse_lazy, reverse
from django.views.decorators.http import require_http_methods
from django.views.generic.dates import ArchiveIndexView, DateDetailView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework.response import Response

from bboard.forms import BbForm, RubricFormSet, RubricForm, RegisterUserForm, LoginUserForm, SearchForm, \
    ProfileUserForm, UploadFileForm, UserSetNewPasswordForm, UserForgotPasswordForm, UserPasswordChangeForm
from bboard.models import Bb, Rubric, UploadFiles
from django.contrib import messages

from bboard.serializers import RubricSerializer, UserSerializer


def index(request):
    rubrics = Rubric.objects.order_by_bb_count()
    paginator = Paginator(rubrics, 6)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    bbs = Bb.objects.order_by('-published')
    context = {'rubrics': page.object_list, 'bbs': bbs, 'page': page}
    return render(request, 'bboard/index.html', context)


class BbIndexView(ArchiveIndexView):
    model = Bb
    date_field = 'published'
    date_list_period = 'year'
    template_name = 'bboard/index.html'
    context_object_name = 'bbs'
    allow_empty = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context




class BbByRubricView(ListView):
    template_name = 'bboard/by_rubric.html'
    context_object_name = 'bbs'
    def get_queryset(self):
        rubric = Rubric.objects.get(pk=self.kwargs['rubric_id'])
        return rubric.bb_set(manager='by_price').all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        context['current_rubric'] = Rubric.objects.get(pk=self.kwargs['rubric_id'])
        paginator = Paginator(self.object_list, 6)

        page_num = self.request.GET.get('page', 1)
        page = paginator.get_page(page_num)

        context['bbs'] = page.object_list
        context['page'] = page
        return context


class RubCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'bboard/create2.html'
    form_class = RubricForm
    success_url = reverse_lazy('bboard:index')
    success_message = 'Рубрика "%(name)s" создана'



class BbCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'bboard/create.html'
    form_class = BbForm
    success_url = '/{rubric_id}'
    success_message = 'Объявление "%(title)s" создано'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context

class BbEditView(LoginRequiredMixin, UpdateView):
    model = Bb
    form_class = BbForm
    success_url = '/{rubric_id}'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context


def commit_handler():
    print('Транзакция закоммичена')


@require_http_methods(['GET', 'POST'])
@login_required(login_url='login')
def edit_rubric(request, pk):
    rubric = Rubric.objects.get(pk=pk)
    if request.method == 'POST':
        form = RubricForm(request.POST, request.FILES, instance=rubric)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Рубрика исправлена!',
                                     extra_tags='alert alert-success')
            messages.success(request, 'Рубрика исправлена!',
                                 extra_tags='alert alert-success')
            return redirect('bboard:index')
    else:
        form = RubricForm(instance=rubric)
    return render(request, 'bboard/edit_rubric.html', {'form': form, 'rubric': rubric})


@require_http_methods(['GET', 'POST'])
@login_required(login_url='login')
def edit(request, pk):
    bb = Bb.objects.get(pk=pk)
    if request.method == 'POST':
        bbf = BbForm(request.POST, request.FILES, instance=bb, )
        if bbf.is_valid():
            if bbf.has_changed():
                bbf.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление исправлено!',
                                     extra_tags='alert alert-success')
                messages.success(request, 'Объявление исправлено!',
                                 extra_tags='alert alert-success')
            return HttpResponseRedirect(
                reverse('bboard:by_rubric', kwargs={'rubric_id': bbf.cleaned_data['rubric'].pk}))
        else:
            context = {'form': bbf}
            return render(request, 'bboard/bb_form.html', context)
    else:
        bbf = BbForm(instance=bb)
        context = {'form': bbf}
        return render(request, 'bboard/bb_form.html', context)


class BbAddView(LoginRequiredMixin, FormView):
    template_name = 'bboard/create.html'
    form_class = BbForm
    initial = {'price': 0.0}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        self.object = super().get_form(form_class)
        return self.object

    def get_success_url(self):
        return reverse('bboard:by_rubric',
                       kwargs={'rubric_id': self.object.cleaned_data['rubric'].pk})


@require_http_methods(['GET', 'POST'])
def add_and_save(request):
    if request.method == 'POST':
        bbf = BbForm(request.POST, request.FILES)

        if bbf.is_valid():
            bbf.save()
            return redirect('bboard:by_rubric',
                            rubric_id=bbf.cleaned_data['rubric'].pk)
        else:
            context = {'form': bbf}
            return render(request, 'bboard/create.html', context)
    else:
        bbf = BbForm()
        context = {'form': bbf}
        return render(request, 'bboard/create.html', context)


def detail(request, bb_id):
    bb = get_object_or_404(Bb, pk=bb_id)

    rubrics = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
    context = {'bb': bb, 'rubrics': rubrics}

    return render(request, 'bboard/detail.html', context)


class BbDetailView(DetailView):
    model = Bb

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context

class UserPasswordChangeView(SuccessMessageMixin, PasswordChangeView):
    """
    Изменение пароля пользователя
    """
    form_class = UserPasswordChangeForm
    template_name = 'registration/user_password_change.html'
    success_message = 'Ваш пароль был успешно изменён!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Изменение пароля на сайте'
        return context

    def get_success_url(self):
        return reverse_lazy('profile')


class BbRedirectView(RedirectView):
    url = '/detail/%(pk)d'


class BbDeleteView(LoginRequiredMixin, DeleteView):
    model = Bb
    success_url = reverse_lazy('bboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context


class RubricDeleteView(LoginRequiredMixin, DeleteView):
    model = Rubric
    success_url = reverse_lazy('bboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubric'] = Rubric.objects.get(pk=self.kwargs['pk'])
        return context



@login_required(login_url='login')
@require_http_methods(['GET', 'POST'])
def rubrics(request):
    rubrics = Rubric.objects.order_by_bb_count()

    paginator = Paginator(rubrics, 6)

    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1

    page = paginator.get_page(page_num)

    bbs = Bb.objects.order_by('-published')

    context = {'rubrics': page.object_list, 'bbs': bbs, 'page': page}

    return render(request, 'bboard/rubrics.html', context)


class Search(ListView):
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:

templates/bboard/Bb_list.html
{% extends 'layout/basic.html' %}
{% block content %}
<div class="rubrics">
   {% for bb in bbs %}
    <div class="rubrica">
        {% url 'bboard:detail' bb.pk as detail_url %}
        <h2>
            <a href="{{ detail_url }}">{{ bb.title }}</a>
        </h2>
        <p>{{ bb.content }}</p>
        {% if bb.photo %}
            <p><img class="imgindetail" src="{{bb.photo.url}}"></p>
        {% endif %}
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        <p><a href="{{ detail_url }}" class="btn btn-primary">Подробнее</a><a href="{% url 'bboard:index' %}"><input type="button" value="Отмена" class="btn btn-primary" /></a></p>
    </div>
    {% empty %}
        <h2>Объявлений нет</h2>
    {% endfor %}
</div>
{% endblock %}
{% block da %}
    <div class="paginator">
        {% if page.has_other_pages %}
        <nav aria-label="pagination" class="pagination">
            <ul class="pagination">

                {% if page.has_previous %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?{{ q }}page={{ page.previous_page_number }}"> < </a>
                    </li>
                {% endif %}

                {% for p in page.paginator.page_range %}
                    {% if not p == page.number %}
                        <li class="page-item">
                            <a class="page-link" href="?{{ q }}page={{ p }}">{{ p }}</a>
                        </li>
                    {% else %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link disabled bg-primary text-light"
                               href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page.has_next %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?{{ q }}page={{ page.next_page_number }}"> > </a>
                    </li>
                {% endif %}

            </ul>
        </nav>
    </div>


    {% endif %}
    {% endblock %}

templates/bboard/about.html
{% extends "layout/basic.html" %}
{% load static %}
{% block net %}
<div class="container_s">

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1294.8490572687936!2d76.8931417167427!3d43.23385837666723!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38836eeeb3600115%3A0x3be664cefb2ff5b6!2sAVSHOP!5e0!3m2!1sru!2skz!4v1706110234938!5m2!1sru!2skz" width="350" height="600" style="border:0; padding-top: 80px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

        <div class="aboutus"><h1>ABOUT US</h1></div>
        <div class="centered" id="text_cl"><h5>Providing our clients with exactly what they want and when they
            want it are the core values that Royal Cars was built.

            We have the largest fleet of luxury hire cars in the Almaty and each vehicle has been
            expertly serviced and maintained to ensure your experience is exceptional and unrivalled.
            </h5></div>
      </div>
<h2 style="text-align:center; padding-top: 40px; padding-bottom: 40px;">Our Team</h2>
<div class="row">
        <div class="column">
          <div class="card">
            <div class="container32">
              <h2>Daniyal Khamidi</h2>
              <p class="title">CEO &amp; Founder</p>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex expedita exercitationem quam odit illum a tenetur sit perferendis, harum adipisci magnam ut sapiente eum provident accusamus, distinctio tempora optio eius.</p>
              <hr>
              <p>Daniyal@example.com</p>
              <p><button class="button">Contact</button></p>
            </div>
          </div>
        </div>

        <div class="column">
          <div class="card">
            <div class="container32">
              <h2>Doudikouv Ivoun</h2>
              <p class="title">Seller</p>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi fugiat, dolores nisi ipsum ullam possimus iusto rerum, totam pariatur culpa atque accusantium tempore a impedit, expedita eaque illum dolorem quo!</p>
              <hr>
              <p>Ivoun@example.com</p>
              <p><button class="button">Contact</button></p>
            </div>
          </div>
        </div>

        <div class="column">
          <div class="card">
            <div class="container32">
              <h2>John Doe</h2>
              <p class="title">Designer</p>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet eos excepturi at et tempore dolorum ea rerum possimus beatae vel neque, molestiae ratione praesentium eaque amet quam debitis. Nulla, blanditiis!</p>
              <hr>
              <p>john@example.com</p>
              <p><button class="button">Contact</button></p>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

templates/bboard/bb_confirm_delete.html
{% extends "layout/basic.html" %}


{% block title %}Удаление объявления{% endblock %}

{% block content %}
<div class="rubrics">
<h2>Удаление объявления</h2>
    <p>Рубрика: {{ bb.rubric.name }}</p>
    <h2>{{ bb.title }}</h2>
    <p>{{ bb.content }}</p>
    <p>Цена: {{ bb.price }} тг.</p>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Удалить</button><a href="{% url 'bboard:index' %}"><input type="button" value="Отмена" class="btn btn-primary" /></a>
    </form>
</div>
{% endblock %}

templates/bboard/bb_form.html
{% extends "layout/basic.html" %}



{% block title %}Изменение объявления{% endblock %}
{% block content %}
<div class="rubrics">
<h2>Изменение объявления</h2>
    <form method="post" enctype="multipart/form-data" class="loginform">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Изменить</button> |
        <a href="{% url 'bboard:index' %}"><input type="button" value="Отмена" class="btn btn-primary" /></a>
    </form>
</div>
{% endblock %}

templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}


{% block content %}
<div class="rubrics">
<h2>{{ current_rubric }}</h2>
    {% for bb in bbs %}
    <div class="rubrica">
        {% url 'bboard:detail' bb.pk as detail_url %}
        <h2>
            <a href="{{ detail_url }}">{{ bb.title }}</a>
        </h2>
        <p>{{ bb.content }}</p>
        {% if bb.photo %}
            <p><img class="imgindetail" src="{{bb.photo.url}}"></p>
        {% endif %}
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        <p><a href="{{ detail_url }}" class="btn btn-primary">Подробнее</a><a href="{% url 'bboard:index' %}"><input type="button" value="Отмена" class="btn btn-primary" /></a></p>
    </div>
    {% empty %}
        <h2>Объявлений нет</h2>
    {% endfor %}
</div>
{% endblock %}

{% block da %}
    <div class="paginator">
        {% if page.has_other_pages %}
        <nav aria-label="pagination" class="pagination">
            <ul class="pagination">

                {% if page.has_previous %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ page.previous_page_number }}"> < </a>
                    </li>
                {% endif %}

                {% for p in page.paginator.page_range %}
                    {% if not p == page.number %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% else %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link disabled bg-primary text-light"
                               href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page.has_next %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ page.next_page_number }}"> > </a>
                    </li>
                {% endif %}

            </ul>
        </nav>

    {% endif %}
            </div>
    {% endblock %}

templates/bboard/create.html
{% extends "layout/basic.html" %}
{% load django_bootstrap5 %}


{% block title %}Добавление объявления{% endblock %}

{% block content %}
<div class="rubrics">
<h2>Добавление объявления</h2>
    <form method="post" enctype="multipart/form-data" class="loginform">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' show_help=False size='sm' %}
        {% bootstrap_button 'Добавить' %}
    </form>
</div>
{% endblock %}

templates/bboard/edit_rubric.html
{% extends "layout/basic.html" %}



{% block title %}Изменение рубрики{% endblock %}
{% block content %}
<div class="rubrics">
<h2>Изменение рубрики</h2>
    <form method="post" enctype="multipart/form-data" class="loginform">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Изменить</button> |
        <a href="{% url 'bboard:delete_rubric' rubric.pk %}" class="btn btn-primary">Удалить</a>
    </form>
</div>
{% endblock %}

templates/bboard/rubrics.html
{% extends "layout/basic.html" %}

{% block content %}
<div class="rubrics">
{% for rubric in rubrics %}
            <div class="b1">
                    <h2>{{rubric.name}}</h2>
                {% if rubric.photo %}
            <a href="{{ rubric.get_absolute_url }}" class="clickable-div">

            <p class="text-on-top"><img class="imginindex" src="{{rubric.photo.url}}"></p>
        {% endif %}

    </a>
        <p><a href="{% url 'bboard:edit_rubric' rubric.pk %}" class="btn btn-primary">Изменить</a>
            <a href="{{ rubric.get_absolute_url }}" class="btn btn-primary">Подробнее</a>
            </a></p>
    </div>
    {% empty %}
        <h2>Рубрик нет</h2>
    {% endfor %}
</div>
{% endblock %}
{% block da %}
    <div class="paginator">
        {% if page.has_other_pages %}
        <nav aria-label="pagination" class="pagination">
            <ul class="pagination">

                {% if page.has_previous %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ page.previous_page_number }}"> < </a>
                    </li>
                {% endif %}

                {% for p in page.paginator.page_range %}
                    {% if not p == page.number %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% else %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link disabled bg-primary text-light"
                               href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page.has_next %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ page.next_page_number }}"> > </a>
                    </li>
                {% endif %}

            </ul>
        </nav>


    {% endif %}
            </div>
    {% endblock %}