bboard/urls.py
from django.urls import path, re_path

from bboard.models import Bb
from bboard.views import (index, BbCreateView,
                          BbByRubricView, BbDetailView,
                          BbDeleteView, BbRedirectView, edit, RubCreateView, rubrics, about,
                          edit_rubric, RubricDeleteView, Search, api_rubrics, api_rubric_detail, UserCreateView, )

app_name = 'bboard'

urlpatterns = [
    path('api/rubrics/<int:pk>/', api_rubric_detail),
    path('api/rubrics/', api_rubrics),
    path('add/', BbCreateView.as_view(), name='add'),
    path('update/<int:pk>/', edit, name='update'),
    path('rubrics/<int:pk>/edit/', edit_rubric, name='edit_rubric'),
    path('rubrics/<int:pk>/delete/', RubricDeleteView.as_view(), name='delete_rubric'),
    path('addrub/', RubCreateView.as_view(), name='addrub'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),
    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),
    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('detail/<int:year>/<int:month>/<int:day>/<int:pk>/',
         BbRedirectView.as_view(), name='old_detail'),
    path('rubrics/', rubrics, name='rubrics'),
    path('', index, name='index'),
    path('search/', Search.as_view(), name='search'),
    path('about/', about, name='about'),
    path('register/', UserCreateView.as_view(), name='user-register'),
]

drfsite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from women.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('api/v1/women/', WomenAPIList.as_view()),
    path('api/v1/women/<int:pk>/', WomenAPIUpdate.as_view()),
    path('api/v1/womendelete/<int:pk>/', WomenAPIDestroy.as_view()),
    path('api/v1/auth/', include('djoser.urls')),  # new
    re_path(r'^auth/', include('djoser.urls.authtoken')),  # new
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

samplesite/urls.py
from tempfile import template

from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include, reverse_lazy

from bboard.views import LoginUser, RegisterUser, ProfileUser, UserForgotPasswordView, UserPasswordResetConfirmView, \
    UserPasswordChangeView
from samplesite import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/login/', LoginUser.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/register/', RegisterUser.as_view(), name='register'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('', include('bboard.urls', namespace='bboard')),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
]
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout/inc/footer.html
<div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col">
                    <h4>компания</h4>
                    <ul>
                        <li><a href="{% url 'bboard:index' %}">Главная</a></li>
                        <li><a href="{% url 'bboard:about' %}">О нас</a></li>
                        <li><a href="">Наши сервисы</a></li>
                        <li><a href="">Отзывы</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>помощь</h4>
                    <ul>
                        <li><a href="">FAQ</a></li>
                        <li><a href="">Отправка</a>
                        </li><li><a href="">Возврат</a></li>
                        <li><a href="">Оплата</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>магазин</h4>
                    <ul>
                        <li><a href="{% url 'bboard:rubrics' %}">Бренды</a></li>
                        <li><a href="">Аксессуары</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>соц сети</h4>
                    <div class="social-links">
                        <a href="#"><img src="icons8-facebook-100.png" alt=""></a>
                        <a href="#"><img src="icons8-instagram-100.png" alt=""></a>
                        <a href="#"><img src="icons8-линкедин-100.png" alt=""></a>
                        <a href="#"><img src="icons8-твиттер-100.png" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/layout/inc/main_menu.html
<div class="header">
    <div class="inner_header">
        <div class="nav">
            <a href="{% url 'bboard:index' %}"><li>Главная</li></a>
            <a href="{% url 'bboard:about' %}"><li>О нас</li></a>
            {% if user.is_anonymous %}
            {% else %}
            {% if perms.catalog.can_create %}
        <a href="{% url 'bboard:add' %}"><li>Добавить объявление</li></a>
        <a href="{% url 'bboard:addrub' %}"><li>Добавить рубрику</li></a>
            <a href="{% url 'bboard:rubrics' %}"><li>Рубрики</li></a>
            {% endif %}
            {% endif %}
            <form action="{% url 'bboard:search' %}" method="get" class="search">
                <input type="search" placeholder="Введите название..." name="q" required="">
                <button type="submit" style="background-color: black; border:none;">
                    <span aria-hidden="true"></span>
                </button>
            </form>
                    {% if user.is_anonymous %}
            <a href="{% url 'login' %}"><li>Войти</li></a>
            <a href="{% url 'register' %}"><li>Регистрация</li></a>
        {% else %}
            <a href="{% url 'profile' %}"><li>{{user.username}}</li></a>
            <a href="{% url 'logout' %}"><li>Выйти</li></a></li>
        {% endif %}
        </div>
    </div>
</div>